version: '3.8'
services:
  bot:
    container_name: tele_bot
    build: ./
    depends_on:
      - db
    volumes:
      - ./bot:/src/bot
    restart: always
    env_file:
      - .env
  db:
    container_name: tele_bot_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - ${PG_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always