# Generated by Django 4.2.13 on 2024-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(),
        ),
    ]
